# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Zone(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, region: str=None):  # noqa: E501
        """Zone - a model defined in Swagger

        :param id: The id of this Zone.  # noqa: E501
        :type id: str
        :param name: The name of this Zone.  # noqa: E501
        :type name: str
        :param region: The region of this Zone.  # noqa: E501
        :type region: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'region': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'region': 'region'
        }
        self._id = id
        self._name = name
        self._region = region

    @classmethod
    def from_dict(cls, dikt) -> 'Zone':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Zone of this Zone.  # noqa: E501
        :rtype: Zone
        """
        return util.deserialize_model(dikt, cls)

    @classmethod
    def from_sa(cls, sa_zone) -> 'Zone':
        """Returns the sa model as a model

        :param dikt: A dict.
        :type: dict
        :return: The Zone of this Zone.  # noqa: E501
        :rtype: Zone
        """
        zone = Zone()
        zone.id = sa_zone.id
        zone.name = sa_zone.name
        zone.region = sa_zone.region.name
        return zone

    @property
    def id(self) -> str:
        """Gets the id of this Zone.


        :return: The id of this Zone.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Zone.


        :param id: The id of this Zone.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Zone.


        :return: The name of this Zone.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Zone.


        :param name: The name of this Zone.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def region(self) -> str:
        """Gets the region of this Zone.


        :return: The region of this Zone.
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region: str):
        """Sets the region of this Zone.


        :param region: The region of this Zone.
        :type region: str
        """

        self._region = region
