openapi: 3.0.3
info:
  title: Testing API
  version: 1.0.0
servers:
- url: https://localhost:8080/api/v1/
paths:
  /zones:
    get:
      tags:
      - Zones
      summary: List zones
      operationId: list_zones
      parameters:
      - name: name
        in: query
        description: Name of the zone
        required: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Zone'
      x-openapi-router-controller: swagger_server.controllers.zones_controller
  /zones/{zone-id}:
    get:
      tags:
      - Zones
      summary: Find zone by id
      operationId: get_zone_by_id
      parameters:
      - name: zone-id
        in: path
        description: ID of zone
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Zone'
      x-openapi-router-controller: swagger_server.controllers.zones_controller
  /zones/{zone-id}/records:
    get:
      tags:
      - Records
      summary: List records in zone
      operationId: list_record
      parameters:
      - name: zone-id
        in: path
        description: ID of zone
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Record'
      x-openapi-router-controller: swagger_server.controllers.records_controller
    post:
      tags:
      - Records
      summary: Create records in zone
      operationId: create_record
      parameters:
      - name: zone-id
        in: path
        description: ID of zone
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecordInput'
      responses:
        "201":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Record'
      x-openapi-router-controller: swagger_server.controllers.records_controller
  /zones/{zone-id}/records/{record-id}:
    get:
      tags:
      - Records
      summary: Find record by id
      operationId: get_record_by_id
      parameters:
      - name: zone-id
        in: path
        description: ID of zone
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: record-id
        in: path
        description: ID of the record
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Record'
      x-openapi-router-controller: swagger_server.controllers.records_controller
    delete:
      tags:
      - Records
      summary: Delete record
      operationId: delete_record
      parameters:
      - name: zone-id
        in: path
        description: ID of zone
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: record-id
        in: path
        description: ID of the record
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "204":
          description: successful operation
      x-openapi-router-controller: swagger_server.controllers.records_controller
components:
  schemas:
    Zone:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 0ce457d8-0c92-46ea-9b00-56fd2bacc335
        name:
          type: string
          example: test.com
        region:
          type: string
          example: paris
      example:
        name: test.com
        id: 0ce457d8-0c92-46ea-9b00-56fd2bacc335
        region: paris
    Record:
      required:
      - name
      - type
      - value
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 0ce457d8-0c92-46ea-9b00-56fd2bacc335
        name:
          type: string
          example: test.com
        value:
          type: string
          example: toto
        type:
          type: string
          example: A
        zoneId:
          type: string
          example: 0ce457d8-0c92-46ea-9b00-56fd2bacc335
    RecordInput:
      required:
        - name
        - type
        - value
      type: object
      properties:
        name:
          type: string
          example: test.com
        type:
          type: string
          example: A
        value:
          type: string
          example: toto

